# A6000-Optimized Configuration for MovieLens RecSys
# Consolidated from base.yaml, development.yaml, and production.yaml

# Model Architecture
model:
  type: "A6000OptimizedVAE"
  n_factors: 200
  hidden_dims: [1024, 512, 256, 128]
  latent_dim: 128
  dropout_rate: 0.4
  use_batch_norm: true
  use_layer_norm: true

# Training Configuration
training:
  batch_size: 2048  # Optimized for A6000 48GB VRAM
  n_epochs: 100
  learning_rate: 0.0003
  weight_decay: 0.0001
  target_rmse: 0.55
  patience: 15
  gradient_clip_norm: 1.0

# VAE Parameters
vae:
  kl_weight: 0.008  # Proven stable value from experiments
  free_bits: 2.0
  adaptive_kl: true
  kl_warmup_epochs: 20

# A6000 GPU Optimizations
gpu:
  use_mixed_precision: true
  allow_tf32: true
  benchmark_cudnn: true
  pin_memory: true
  num_workers: 8
  persistent_workers: true

# Data Configuration
data:
  processed_dir: "data/processed"
  train_file: "train_data.csv"
  val_file: "val_data.csv"
  test_file: "test_data.csv"
  mappings_file: "data_mappings.pkl"

# Experiment Tracking
tracking:
  use_wandb: true
  project_name: "movielens-a6000-training"
  log_frequency: 100  # Log every N batches
  save_checkpoints: true
  checkpoint_frequency: 10  # Save every N epochs

# Output Configuration
output:
  models_dir: "models/a6000_trained"
  logs_dir: "logs"
  results_dir: "results"
  save_best_only: true

# Performance Targets
targets:
  rmse_breakthrough: 0.55
  rmse_advanced: 0.50
  precision_at_10: 0.40
  ndcg_at_10: 0.45

# Hardware Specifications
hardware:
  target_gpu: "RTX A6000"
  vram_gb: 48
  recommended_batch_sizes:
    conservative: 1536
    optimal: 2048
    aggressive: 2560
  estimated_training_time_hours: 4-6

# Legacy Experiment Mapping (for reference)
legacy_experiments:
  hybrid_vae_v1_20250815_140527:
    rmse: 0.806
    status: "completed"
    notes: "Baseline with overfitting issues"
  
  hybrid_vae_v2_20250815_140527:
    rmse: null
    status: "failed"
    notes: "Advanced regularization - index error"
  
  rmse_breakthrough_experiments:
    target: 0.55
    status: "planned"
    config_template: "hybrid_vae_optimized"