# Base Configuration
# Common settings shared across all environments

environment:
  debug: true
  testing: false
  log_level: "DEBUG"

# Model serving defaults
model_serving:
  host: "127.0.0.1"
  port: 8501
  max_workers: 2
  timeout: 30
  enable_cors: true

# Model defaults
models:
  default_model: "matrix_factorization"
  model_cache_size: 2
  inference_timeout_ms: 100
  batch_size: 32
  
  model_directory: "data/models"
  active_model_path: "data/models/{model_name}_active.pt"
  
  supported_types:
    - "matrix_factorization"
    - "neural_cf"
    - "two_tower"
    - "hybrid_vae"

# Data defaults
data:
  processed_data_dir: "data/processed"
  raw_data_dir: "data/raw"
  cache_dir: "data/processed/cache"
  
  dataset_version: "latest"
  min_rating_threshold: 3.0
  min_user_interactions: 20
  min_item_interactions: 5
  
  enable_data_validation: true
  max_missing_ratio: 0.05
  quality_threshold: 0.8

# Business thresholds (from GAMEPLAN.md)
business_thresholds:
  min_precision_at_10: 0.35
  min_ndcg_at_10: 0.42
  max_rmse: 0.85
  min_diversity: 0.50
  min_coverage: 0.60
  
  min_revenue_impact: 500000
  min_ctr_improvement: 0.05
  min_session_duration_boost: 0.15
  
  max_inference_time_ms: 50.0
  max_model_size_mb: 1000.0
  min_training_stability: 0.95
  max_training_time_hours: 2.0

# Monitoring defaults
monitoring:
  enable_drift_detection: false
  drift_detection_schedule: "0 6 * * *"
  drift_sensitivity: "medium"
  
  enable_data_quality_monitoring: false
  quality_check_interval_hours: 4
  min_data_quality_score: 0.80
  
  enable_business_monitoring: false
  baseline_ctr: 0.30
  baseline_session_duration: 25.0
  
  alert_email: ""
  slack_webhook_url: ""
  alert_thresholds:
    critical_drift_score: 0.15
    warning_drift_score: 0.10
    critical_quality_score: 0.70
    warning_quality_score: 0.80

# Training defaults
training:
  device: "cpu"
  mixed_precision: false
  compile_model: false
  
  default_params:
    batch_size: 1024
    learning_rate: 0.001
    max_epochs: 50
    early_stopping_patience: 5
    weight_decay: 0.0001
    
  matrix_factorization:
    embedding_dim: 64
    reg_lambda: 0.01
    
  neural_cf:
    embedding_dim: 64
    hidden_dims: [128, 64, 32]
    dropout: 0.2
    
  two_tower:
    user_embedding_dim: 64
    item_embedding_dim: 64
    hidden_dim: 128
    
  hybrid_vae:
    latent_dim: 32
    encoder_dims: [128, 64]
    decoder_dims: [64, 128]
    beta: 0.1

# Database defaults
database:
  enable_database: false
  connection_string: ""
  connection_pool_size: 10
  query_timeout: 30
  
  tables:
    ratings: "ratings"
    users: "users"
    movies: "movies"
    predictions: "predictions"

# Caching defaults
caching:
  enable_redis: false
  redis_url: ""
  cache_ttl: 3600
  max_cache_size_mb: 512
  
  enable_local_cache: true
  local_cache_size: 1000
  local_cache_ttl: 300

# Security defaults
security:
  enable_https: false
  ssl_cert_path: ""
  ssl_key_path: ""
  
  enable_rate_limiting: false
  rate_limit_per_minute: 100
  enable_cors: true
  allowed_origins: []
  
  enable_auth: false
  jwt_secret: ""
  token_expiry: 3600

# Logging defaults
logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  enable_json_logging: false
  log_file: ""
  max_log_size_mb: 100
  backup_count: 5
  
  include_fields:
    - "timestamp"
    - "level"
    - "logger"
    - "message"

# Performance defaults
performance:
  max_threads: 4
  enable_multiprocessing: false
  
  max_memory_usage_gb: 4
  garbage_collection_threshold: 0.8
  
  max_concurrent_requests: 50
  request_timeout: 30
  keep_alive_timeout: 5

# Feature flags defaults
feature_flags:
  enable_experimental_models: false
  enable_ab_testing: false
  enable_personalization: true
  enable_cold_start_handling: true
  enable_popularity_fallback: true
  enable_diversity_boosting: false

# Deployment defaults
deployment:
  strategy: "replace"
  max_unavailable: 1
  max_surge: 1
  
  health_check_path: "/health"
  readiness_check_path: "/ready"
  liveness_check_path: "/live"
  
  min_replicas: 1
  max_replicas: 3
  target_cpu_utilization: 70
  target_memory_utilization: 80
  
  enable_auto_rollback: false
  rollback_threshold_error_rate: 0.10
  rollback_threshold_latency_ms: 200

# Backup defaults
backup:
  enable_model_backup: false
  backup_schedule: "0 2 * * *"
  retention_days: 7
  backup_location: ""
  
  enable_cross_region_backup: false
  recovery_time_objective_hours: 24
  recovery_point_objective_hours: 24

# Compliance defaults
compliance:
  enable_audit_logging: false
  enable_data_lineage: false
  enable_model_explainability: false
  enable_bias_detection: false
  
  user_data_retention_days: 365
  model_retention_days: 90
  log_retention_days: 30