# Production Configuration
# Environment settings for production deployment

environment:
  name: "production"
  debug: false
  testing: false
  log_level: "INFO"

# Model serving configuration
model_serving:
  host: "0.0.0.0"
  port: 8501
  max_workers: 4
  timeout: 30
  enable_cors: false
  
# Model configuration
models:
  default_model: "matrix_factorization"
  model_cache_size: 3  # Number of models to keep in memory
  inference_timeout_ms: 50
  batch_size: 64
  
  # Model paths
  model_directory: "data/models"
  active_model_path: "data/models/{model_name}_active.pt"
  
  # Supported model types
  supported_types:
    - "matrix_factorization"
    - "neural_cf" 
    - "two_tower"
    - "hybrid_vae"

# Data configuration
data:
  # Data paths
  processed_data_dir: "data/processed"
  raw_data_dir: "data/raw"
  cache_dir: "data/processed/cache"
  
  # MovieLens dataset configuration
  dataset_version: "latest"
  min_rating_threshold: 3.0
  min_user_interactions: 20
  min_item_interactions: 5
  
  # Data validation
  enable_data_validation: true
  max_missing_ratio: 0.05
  quality_threshold: 0.8

# Business thresholds (from GAMEPLAN.md)
business_thresholds:
  # Core performance metrics
  min_precision_at_10: 0.35
  min_ndcg_at_10: 0.42  
  max_rmse: 0.85
  min_diversity: 0.50
  min_coverage: 0.60
  
  # Business impact metrics
  min_revenue_impact: 500000  # Annual revenue impact ($)
  min_ctr_improvement: 0.05   # 5% CTR improvement
  min_session_duration_boost: 0.15  # 15% session duration boost
  
  # Operational thresholds
  max_inference_time_ms: 50.0
  max_model_size_mb: 1000.0
  min_training_stability: 0.95
  max_training_time_hours: 2.0

# Monitoring configuration
monitoring:
  enable_drift_detection: true
  drift_detection_schedule: "0 6 * * *"  # Daily at 6 AM UTC
  drift_sensitivity: "medium"
  
  # Data quality monitoring
  enable_data_quality_monitoring: true
  quality_check_interval_hours: 4
  min_data_quality_score: 0.80
  
  # Business metrics monitoring  
  enable_business_monitoring: true
  baseline_ctr: 0.30
  baseline_session_duration: 25.0
  
  # Alert configuration
  alert_email: "ml-team@company.com"
  slack_webhook_url: ""  # Configure in secrets
  alert_thresholds:
    critical_drift_score: 0.15
    warning_drift_score: 0.10
    critical_quality_score: 0.70
    warning_quality_score: 0.80

# Model training configuration
training:
  # Training environment
  device: "cpu"  # Use "cuda" if GPU available
  mixed_precision: false
  compile_model: false
  
  # Hyperparameter defaults
  default_params:
    batch_size: 1024
    learning_rate: 0.001
    max_epochs: 50
    early_stopping_patience: 5
    weight_decay: 0.0001
    
  # Model-specific configurations
  matrix_factorization:
    embedding_dim: 64
    reg_lambda: 0.01
    
  neural_cf:
    embedding_dim: 64
    hidden_dims: [128, 64, 32]
    dropout: 0.2
    
  two_tower:
    user_embedding_dim: 64
    item_embedding_dim: 64
    hidden_dim: 128
    
  hybrid_vae:
    latent_dim: 32
    encoder_dims: [128, 64]
    decoder_dims: [64, 128]
    beta: 0.1

# Database configuration (if using external DB)
database:
  enable_database: false  # Set to true for external DB
  connection_string: ""   # Configure in secrets
  connection_pool_size: 10
  query_timeout: 30
  
  # Tables
  tables:
    ratings: "ratings"
    users: "users" 
    movies: "movies"
    predictions: "predictions"

# Caching configuration
caching:
  enable_redis: false  # Set to true for Redis caching
  redis_url: ""       # Configure in secrets
  cache_ttl: 3600     # 1 hour
  max_cache_size_mb: 512
  
  # Local caching
  enable_local_cache: true
  local_cache_size: 1000
  local_cache_ttl: 300  # 5 minutes

# Security configuration
security:
  enable_https: true
  ssl_cert_path: "/etc/ssl/cert.pem"  # Configure for production
  ssl_key_path: "/etc/ssl/key.pem"   # Configure for production
  
  # API security
  enable_rate_limiting: true
  rate_limit_per_minute: 100
  enable_cors: false
  allowed_origins: []
  
  # Authentication (if required)
  enable_auth: false
  jwt_secret: ""      # Configure in secrets
  token_expiry: 3600

# Logging configuration  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  enable_json_logging: true
  log_file: "/var/log/movielens-recsys.log"
  max_log_size_mb: 100
  backup_count: 5
  
  # Structured logging fields
  include_fields:
    - "timestamp"
    - "level"
    - "logger"
    - "message"
    - "user_id"
    - "request_id" 
    - "model_version"
    - "response_time"

# Performance configuration
performance:
  # Threading
  max_threads: 8
  enable_multiprocessing: false
  
  # Memory management
  max_memory_usage_gb: 8
  garbage_collection_threshold: 0.8
  
  # Request handling
  max_concurrent_requests: 100
  request_timeout: 30
  keep_alive_timeout: 5

# Feature flags
feature_flags:
  enable_experimental_models: false
  enable_ab_testing: false
  enable_personalization: true
  enable_cold_start_handling: true
  enable_popularity_fallback: true
  enable_diversity_boosting: true

# Deployment configuration
deployment:
  # Deployment strategy
  strategy: "rolling_update"
  max_unavailable: 1
  max_surge: 1
  
  # Health checks
  health_check_path: "/health"
  readiness_check_path: "/ready"
  liveness_check_path: "/live"
  
  # Scaling
  min_replicas: 2
  max_replicas: 10
  target_cpu_utilization: 70
  target_memory_utilization: 80
  
  # Rollback configuration
  enable_auto_rollback: true
  rollback_threshold_error_rate: 0.05  # 5% error rate
  rollback_threshold_latency_ms: 100   # 100ms p95 latency

# Backup and disaster recovery
backup:
  enable_model_backup: true
  backup_schedule: "0 2 * * *"  # Daily at 2 AM UTC
  retention_days: 30
  backup_location: "s3://movielens-model-backups/"  # Configure for production
  
  # Disaster recovery
  enable_cross_region_backup: false
  recovery_time_objective_hours: 4
  recovery_point_objective_hours: 1

# Compliance and governance
compliance:
  enable_audit_logging: true
  enable_data_lineage: true
  enable_model_explainability: false
  enable_bias_detection: false
  
  # Data retention
  user_data_retention_days: 2555  # 7 years
  model_retention_days: 365       # 1 year
  log_retention_days: 90          # 3 months