_wandb:
    value:
        cli_version: 0.21.1
        e:
            0lunavy7jp6ylm6wd4ke2c5rp1duayr4:
                codePath: runpod_training_wandb.py
                codePathLocal: runpod_training_wandb.py
                cpu_count: 252
                cpu_count_logical: 252
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "32212254720"
                        used: "618655744"
                email: nolanrobbins5934@gmail.com
                executable: /usr/bin/python
                git:
                    commit: a65ab6af77e9158e025abdd89861830d8f9570fe
                    remote: https://github.com/NolanRobbins/MovieLens-RecSys.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-80157493-aaf0-eb27-5d29-0fa2bbf20c4e
                host: e2e2b0385ee6
                memory:
                    total: "1014068436992"
                os: Linux-6.8.0-65-generic-x86_64-with-glibc2.35
                program: /MovieLens-RecSys/runpod_training_wandb.py
                python: CPython 3.11.11
                root: /MovieLens-RecSys
                startedAt: "2025-08-15T18:05:01.658378Z"
                writerId: 0lunavy7jp6ylm6wd4ke2c5rp1duayr4
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 2
                - 13
                - 15
                - 16
            "4": 3.11.11
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
batch_size:
    value: 6144
dropout_rate:
    value: 0.38
gpu_monitoring:
    value: true
gradient_clipping:
    value: true
hidden_dims:
    value:
        - 640
        - 384
        - 192
kl_warmup_epochs:
    value: 20
kl_weight:
    value: 0.008
latent_dim:
    value: 80
log_interval:
    value: 100
lr:
    value: 0.0002
mixed_precision:
    value: false
n_epochs:
    value: 100
n_factors:
    value: 160
num_workers:
    value: 8
patience:
    value: 15
pin_memory:
    value: true
save_interval:
    value: 10
target_rmse:
    value: 0.55
tf32_enabled:
    value: true
weight_decay:
    value: 1e-05
