[global]
# Production configuration for Streamlit Cloud
developmentMode = false

[server]
headless = true
enableCORS = false
port = 8501
maxUploadSize = 1000

[browser]
gatherUsageStats = false
showErrorDetails = true

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[logger]
level = "info"