# Streamlit Cloud Secrets Configuration
# Add these secrets in your Streamlit Cloud dashboard

# Example structure - DO NOT commit real secrets to git
[secrets]
# GitHub token for API access (if needed)
# github_token = "your_github_token_here"

# Model storage configuration
# model_storage_path = "data/models"
# cache_storage_path = "data/processed/cache"

# Production environment settings
environment = "production"
debug_mode = false

# Business metrics configuration
[business]
baseline_ctr = 0.30
baseline_session_duration = 25.0
target_revenue_impact = 500000

[monitoring]
enable_drift_detection = true
drift_sensitivity = "medium"
alert_email = "your-email@example.com"

# Note: This is a template file
# Real secrets should be configured in Streamlit Cloud dashboard
# under "Secrets management" section